channels:
  - conda-forge
  - bioconda
  - nodefaults

name: cubi-tk

dependencies:
  - python ~=3.12
  - pip
  - uv >=0.8.18
  - pysam >=0.22
  - vcfpy >=0.13.8
  - gcc_linux-64 >=13,<14
  - zlib ~=1.3.0
  - liblzma ~=5.6.3
