on:
  push:
    branches:
      - main

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:

      - uses: GoogleCloudPlatform/release-please-action@v4
        id: release
        with:
          release-type: python

  pypi-publish:
    if: ${{ needs.release-please.outputs.release_created }}
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    needs: release-please
    environment:
      name: pypi
      url: https://pypi.org/p/cubi-tk
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.23"
          enable-cache: true
          python-version: 3.12

      - name: Build package
        run: |
          uv build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
